services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    entrypoint: /bin/bash
    working_dir: "/app"
    depends_on:
      epsilon: 
        condition: service_healthy
    volumes:
      - "./:/app:rw"
#    network_mode: service:epsilon

  epsilon:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    entrypoint: /bin/bash
    working_dir: "/app"
    volumes:
      - "./:/app:rw"
    command: ".buildkite/scripts/run.sh Epsilon"
    healthcheck:
      test: curl --fail -k http://localhost:5172/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - dbPostgres
#    network_mode: service:dbPostgres
      
  dbPostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: EpsilonDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
