steps:
  - label: ":test_tube: Dotnet Test"
    key: "tests"
    command:
      - make test
    artifact_paths:
      - "*/coverage.opencover.xml"
    concurrency_group: "epsilon_test"

  - label: ":test_tube: Integration Tests"
    command:
      - make integration-test
    concurrency_group: "epsilon_integration_test"

  - label: ":test_tube: Stryker Test"
    command:
      - make stryker
    artifact_paths:
      - "**/mutation-report.html"
    concurrency_group: "epsilon_stryker"

  - label: ":sonarqube: Sonarqube Scanner"
    depends_on: 
      - "tests"
    command:
      - buildkite-agent artifact download **/*opencover.xml .
      - make sonarqube
    concurrency_group: "epsilon_sonarqube"
