steps:
  - label: ":test_tube: Dotnet Test"
    key: "tests"
    command:
      - make test
    artifact_paths:
      - "*/coverage.opencover.xml"

  - label: ":test_tube: Integration Tests"
    command:
      - make integration-test
    artifact_paths:
      - "*/coverage.opencover.xml"

  - label: ":test_tube: Stryker Test"
    command:
      - make stryker
    artifact_paths:
      - "**/mutation-report.html"

  - label: ":sonarqube: Sonarqube Scanner"
    depends_on: 
      - "tests"
    command:
      - buildkite-agent artifact download **/*opencover.xml .
      - make sonarqube
    artifact_paths:
      - "**/mutation-report.html"