name: Dotnet Format
permissions:
  contents: write
'on':
  push:
    branches:
      - '*'
      - '!main'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
      - name: Run dotnet format
        run: dotnet format
      - name: Commit and push changes
        run: >
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff-index --quiet HEAD; then
            git add .
            git commit -m "Apply dotnet format"
            git push
          else
            echo "No changes to commit"